popserver6969:
	gcc -o popserver popserver.c
	./popserver 6969

popserver9000:
	gcc -o popserver popserver.c
	./popserver 9000

popserver1729:
	gcc -o popserver popserver.c
	./popserver 1729

smtpserver2525:
	gcc -o smtpserver smtpserver.c
	./smtpserver 2525

smtpserver4200:
	gcc -o smtpserver smtpserver.c
	./smtpserver 4200

smtpserver8080:
	gcc -o smtpserver smtpserver.c
	./smtpserver 8080

clean:
	rm -f popserver smtpserver